language: scala

scala:
- 2.10.5
- 2.11.7

before_cache:
- du -h -d 1 $HOME/.ivy2/cache
- du -h -d 2 $HOME/.sbt/
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/0.13/dependency
  - $HOME/.sbt/boot/
  - $HOME/.sbt/launchers
  - $HOME/android-sdk_r24-linux.tgz
  - $HOME/android-sdk-linux

before_install:
- sudo apt-get update -qq
- sudo apt-get install -y libc6-i386 lib32z1 lib32stdc++6
- bash project/prepare-build.sh
- export ANDROID_HOME=$HOME/android-sdk-linux
- export ANDROID_SDK_HOME=$HOME/android-sdk-linux
- export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools

